stages:
  process-prices:
    cmd: Rscript R/process-prices.R
    deps:
      - R/process-prices.R
      - data/raw-survey-prices.parquet
    outs:
      - data/survey-prices.parquet
  make-geks:
    cmd: Rscript R/make-geks.R
    deps:
      - R/make-geks.R
      - data/scanner-prices.parquet
    outs:
      - data/geks.parquet
  make-index:
    cmd: Rscript R/make-index.R
    deps:
      - R/make-index.R
      - data/survey-prices.parquet
      - data/geks.parquet
      - data/weights.parquet
    outs:
      - data/index.parquet
      - data/contributions.parquet